Repository gwastro/pycbc, pull requests merged in 2018-08, with the labels that each got.

#2276 fixes to make test fftw unthreaded work in python3
  pycbc/fft/core.py
  pycbc/types/aligned.py
Labels: python3

#2266 Add low-frequency cutoff option for every detector
  bin/inference/pycbc_inference
  pycbc/inference/likelihood.py
  pycbc/inference/option_utils.py
  test/test_inference.py
Labels: inference

#2277 add support for injection / distribution tests, start on p3 tmpltbank test
  examples/psd/estimate.py
  pycbc/distributions/__init__.py
  pycbc/distributions/bounded.py
  pycbc/tmpltbank/brute_force_methods.py
  pycbc/tmpltbank/calc_moments.py
  pycbc/tmpltbank/coord_utils.py
  pycbc/tmpltbank/lambda_mapping.py
  pycbc/types/array.py
  pycbc/types/frequencyseries.py
  pycbc/types/timeseries.py
  pycbc/workflow/configuration.py
  test/test_distributions.py
  test/test_injection.py
  test/test_tmpltbank.py
Labels: python3

#2280 Use data from LOSC to check the workflow
  bin/pycbc_losc_segment_query
  tools/docker_build_dist.sh
  tools/test_coinc_search_workflow.sh
Labels: work in progress

#2291 Make ensurearray more numpy like
  pycbc/conversions.py
  pycbc/distributions/spins.py
Labels: enhancement
