Repository gwastro/pycbc, pull requests merged in 2019-08, with the labels that each got.

#2872 add in pycbc_multiifo_exclude_zerolag executable
  bin/hdfcoinc/pycbc_multiifo_exclude_zerolag
  bin/workflows/pycbc_create_offline_search_workflow
  pycbc/io/hdf.py
  pycbc/workflow/coincidence.py
Labels: offline search

#2880 Tag empty string removal
  pycbc/workflow/core.py
Labels: bug

#2881 Exclude zerolag not dealing with DictArray properly
  bin/hdfcoinc/pycbc_multiifo_exclude_zerolag
Labels: bug, offline search

#2884 add_statmap fap calculation
  bin/hdfcoinc/pycbc_multiifo_add_statmap
Labels: offline search

#2888 Inference warning when parameter repeated
  pycbc/distributions/__init__.py
Labels: inference

#2889 PyCBC Live autogating fixes
  bin/pycbc_live
  pycbc/strain/strain.py
Labels: low latency

#2891 Fix bug in PyCBC Live autogating
  pycbc/strain/strain.py
Labels: low latency

#2910 recalculation of exclusive IFAR/FAP in exclude_zerolag
  bin/hdfcoinc/pycbc_multiifo_exclude_zerolag
Labels: offline search
