Repository gwastro/pycbc, pull requests merged in 2019-11, with the labels that each got.

#2982 Fix plot psd for inference files
  bin/hdfcoinc/pycbc_plot_psd_file
Labels: bug

#2992 Fix python3-ism in 2991
  bin/pycbc_live
Labels: low latency, python3

#2993 PyCBC Live: fix errors from SNR optimization in Python 3
  bin/pycbc_live
  bin/pycbc_optimize_snr
  pycbc/io/live.py
Labels: bug, low latency

#3003 PyCBC Live: misc improvements
  bin/pycbc_live
  pycbc/frame/frame.py
  pycbc/io/live.py
Labels: enhancement, low latency

#3019 Add background coinc pages to multiifo workflow
  bin/workflows/pycbc_create_offline_search_workflow
Labels: offline search
