Repository gwastro/pycbc, pull requests merged in 2019-07, with the labels that each got.

#2817 dont get rid of segments bit of combine statmap
  bin/hdfcoinc/pycbc_multiifo_combine_statmap
Labels: offline search

#2823 Fix error in autogating & minor cleanup
  pycbc/strain/strain.py
Labels: bug

#2811 adding add_statmap code
  bin/hdfcoinc/pycbc_multiifo_add_statmap
  pycbc/events/stat.py
Labels: offline search

#2831 exp_fit_sg_coinc_rate stat Inf issue
  pycbc/events/coinc_rate.py
  pycbc/events/stat.py
Labels: bug, offline search

#2814 workflow components to apply follow-up of background / zerolag and rerank
  bin/hdfcoinc/pycbc_apply_rerank
  bin/hdfcoinc/pycbc_followup_file
  bin/hdfcoinc/pycbc_rerank_passthrough
  bin/workflows/pycbc_create_offline_search_workflow
  bin/workflows/pycbc_make_coinc_search_workflow
  pycbc/frame/store.py
  pycbc/psd/estimate.py
  pycbc/workflow/coincidence.py
Labels: offline search

#2834 Add statmap inj
  bin/hdfcoinc/pycbc_multiifo_add_statmap
  bin/workflows/pycbc_create_offline_search_workflow
  pycbc/io/hdf.py
  pycbc/workflow/coincidence.py
Labels: offline search

#2843 add median_sigma to fit_by_template and fit_over_multiparam
  bin/hdfcoinc/pycbc_fit_sngls_by_template
  bin/hdfcoinc/pycbc_fit_sngls_over_multiparam
Labels: offline search

#2840 Fix inference_inj_workflow bug
  bin/workflows/pycbc_make_inference_inj_workflow
Labels: bug, inference

#2850 add in sigma variation into statistic
  pycbc/events/coinc_rate.py
  pycbc/events/stat.py
Labels: offline search

#2860 Sensitivity plots fix
  bin/workflows/pycbc_create_offline_search_workflow
Labels: offline search

#2627 Adding autogating to PyCBC Live
  bin/pycbc_live
  pycbc/strain/strain.py
Labels: low latency

#2873 Fix invcdf in Gaussian distribution
  pycbc/distributions/gaussian.py
Labels: bug

#2877 rename table function and table module to prevent clashes
  bin/hdfcoinc/pycbc_page_foreground
  bin/hdfcoinc/pycbc_page_injtable
  bin/hdfcoinc/pycbc_page_segtable
  bin/hdfcoinc/pycbc_page_vetotable
  bin/plotting/pycbc_banksim_table_point_injs
  pycbc/results/__init__.py
  pycbc/results/table_utils.py
Labels: bug
