Repository gwastro/pycbc, pull requests merged in 2019-12, with the labels that each got.

#3022 add_statmap outputs background_exc
  bin/hdfcoinc/pycbc_multiifo_add_statmap
Labels: offline search

#3023 Fix live snr opt and to use with injections without GraceDB uploads
  README.md
  bin/pycbc_live
  bin/pycbc_optimize_snr
  pycbc/__init__.py
Labels: low latency

#3044 Injections are optional, fix inj_summ var
  bin/workflows/pycbc_create_offline_search_workflow
Labels: bug

#3057 Added Injection f-ref option to multi-ifo strain function
  pycbc/strain/strain.py
Labels: inference

#3059 Fix Workflow.save_config for python3
  pycbc/workflow/core.py
Labels: python3

#2980 Live trigger ifar calculation
  bin/pycbc_live
  pycbc/events/single.py
Labels: low latency

#3062 Fix empty git info when using Python 3
  pycbc/_version_helper.py
Labels: bug, python3
