Repository gwastro/pycbc, pull requests merged in 2019-03, with the labels that each got.

#2534 Use automatically determined number of sig. figs in posterior titles
  pycbc/results/scatter_histograms.py
  pycbc/results/str_utils.py
Labels: enhancement, inference

#2527 Priors on 1D marginal posterior plots
  bin/inference/pycbc_inference_plot_posterior
  bin/inference/pycbc_inference_plot_prior
  pycbc/inference/option_utils.py
  pycbc/results/scatter_histograms.py
Labels: inference

#2513 Quick fix for SNR in plot_posterior
  bin/inference/pycbc_inference_plot_posterior
  pycbc/inference/io/base_hdf.py
Labels: bug, inference

#2564 Try to fix occasional error described in #2554
  pycbc/frame/frame.py
Labels: low latency

#2565 Fix wrong call to is_extent_valid()
  pycbc/filter/matchedfilter.py
Labels: low latency

#2550 Adding/fixing phasetd_newsnr_sgveto for PyCBC Live
  pycbc/events/coinc.py
  pycbc/events/stat.py
  pycbc/filter/matchedfilter.py
  pycbc/vetoes/sgchisq.py
Labels: low latency

#2561 Fix various errors in PyCBC Live
  bin/pycbc_live
  pycbc/events/single.py
  pycbc/types/timeseries.py
Labels: low latency

#2548 Add back ability to provide beta values to emcee_pt from external file
  pycbc/inference/sampler/emcee_pt.py
Labels: inference

#2562 Load constraints when reading prior from config for plotting
  pycbc/inference/option_utils.py
Labels: inference

#2575 broadcast start time for pycbc live
  bin/pycbc_live
Labels: low latency

#2572 add option to limit which coincs to follow-up with multiifos
  bin/pycbc_live
Labels: low latency

#2580 PyCBC Live creates SNR time series with slightly different sample period
  bin/pycbc_live
  pycbc/filter/matchedfilter.py
Labels: low latency

#2586 Corrects an error caused by pull request #2562.
  bin/inference/pycbc_inference_plot_prior
  pycbc/inference/option_utils.py
Labels: bug, inference

#2585 Make low frequency cutoff required when using data in pycbc inference
  bin/inference/pycbc_inference
  pycbc/inference/option_utils.py
Labels: inference

#2577 based duration on template length
  pycbc/filter/matchedfilter.py
Labels: low latency, work in progress

#2592 Force PyCBC Live's SNR series to have identical sampling
  bin/pycbc_live
  pycbc/io/live.py
Labels: low latency

#2605 Change suggested number of walkers and burn in
  examples/inference/bbh-injection/inference.ini
Labels: inference

#2606 Use config argument group in pycbc inference
  bin/inference/pycbc_inference
  pycbc/inference/option_utils.py
  pycbc/workflow/configuration.py
Labels: inference

#2608 Handle cases where master and worker nodes disagree on ifo status
  bin/pycbc_live
Labels: low latency
