Repository gwastro/pycbc, pull requests merged in 2019-09, with the labels that each got.

#2921 PyCBC Live: fix issue in how the detector state is reported
  bin/pycbc_live
  pycbc/events/stat.py
Labels: low latency

#2923 Remove exclude foreground from workflow if only one coincidence type
  bin/workflows/pycbc_create_offline_search_workflow
Labels: bug, offline search

#2897 Fix issue with invalid checkpoint file raising error
  pycbc/inference/sampler/base.py
Labels: bug, inference

#2940 two ifo coinc should still pass ifos
  bin/hdfcoinc/pycbc_coinc_findtrigs
Labels: offline search

#2939 add statmap doesn't work when using two ifos (in multi-ifo workflow).
  bin/hdfcoinc/pycbc_multiifo_add_statmap
Labels: offline search

#2913 Injection and foreground minifollowups missing triggers/data
  bin/minifollowups/pycbc_foreground_minifollowup
  bin/minifollowups/pycbc_injection_minifollowup
Labels: offline search

#2956 Add pruning in to fit_sngls_split_binned
  bin/hdfcoinc/pycbc_fit_sngls_split_binned
Labels: offline search
