Repository gwastro/pycbc, pull requests merged in 2019-04, with the labels that each got.

#2607 Pycbc inference injection workflow documentation fix
  docs/workflow/pycbc_make_inference_inj_workflow.rst
  examples/workflow/inference_inj/inference.ini
  examples/workflow/inference_inj/run_pycbc_make_inference_inj_workflow.sh
  examples/workflow/inference_inj/workflow_config.ini
Labels: inference

#2610 remove expired elements only when trying to read data, no log with sl…
  pycbc/events/coinc.py
Labels: low latency

#2620 Fix import error due to #2602
  bin/pycbc_live
Labels: low latency

#2619 spread coinc ops over multiple processors
  bin/pycbc_live
  pycbc/events/coinc.py
  pycbc/pool.py
Labels: low latency

#2624 Bug in _HDFInjectionSet
  pycbc/inject/inject.py
Labels: bug

#2629 fix import in fit_by_template
  bin/hdfcoinc/pycbc_fit_sngls_by_template
Labels: bug

#2632 Live: check outcome of followup p-value calculation before using it
  bin/pycbc_live
Labels: low latency

#2412 Add final mass/spin from initial parameters to conversions
  pycbc/conversions.py
Labels: enhancement

#2633 Unify CBC and ringdown injection interface
  bin/pycbc_create_injections
  bin/pycbc_ringinj
  pycbc/inject/inject.py
  pycbc/strain/strain.py
Labels: enhancement

#2628 Add basic plots to GraceDB uploads
  pycbc/io/live.py
Labels: low latency

#2641 Live: avoid human confusion with χ² not being calculated
  bin/pycbc_live
  pycbc/filter/matchedfilter.py
Labels: low latency

#2571 Enable the basic pycbc_live --help test
  .travis.yml
  tools/install_travis.sh
  tools/pycbc_test_suite.sh
Labels: low latency

#2648 Fixing some Python 3 errors in PyCBC Live
  bin/pycbc_live
  pycbc/io/record.py
  pycbc/vetoes/__init__.py
Labels: python3

#2636 Live: enable per-detector analysis flags
  bin/pycbc_live
  pycbc/filter/matchedfilter.py
  pycbc/frame/__init__.py
  pycbc/frame/frame.py
  pycbc/strain/strain.py
Labels: low latency

#2656 Bug in pycbc_page_coincinfo for 2-ifo workflow
  bin/minifollowups/pycbc_page_coincinfo
Labels: bug

#2660 reduce memory useage of fit by template
  bin/hdfcoinc/pycbc_fit_sngls_by_template
Labels: offline search
