Repository gwastro/pycbc, pull requests merged in 2020-05, with the labels that each got.

#3229 Updates to snrratehist
  bin/hdfcoinc/pycbc_page_snrratehist
Labels: offline search

#3255 Add basic example/test of PyCBC Live
  examples/live/run.sh
  tools/pycbc_test_suite.sh
Labels: low latency

#3257 Allow PE to continue if waveform fails
  pycbc/inference/models/gaussian_noise.py
  pycbc/inference/models/marginalized_gaussian_noise.py
  pycbc/waveform/generator.py
  pycbc/waveform/waveform.py
Labels: enhancement, inference

#3228 No longer round sample rate
  pycbc/strain/strain.py
  pycbc/types/timeseries.py
  test/test_chisq.py
Labels: LISA, bug, low latency

#3258 Fix issue #3248
  pycbc/inference/models/data_utils.py
Labels: bug, inference

#3264 PyCBC Live: fix empty versions in uploads
  pycbc/io/live.py
Labels: low latency

#3262 updated inverse cdf interfaces so we can support correlated parameters
  pycbc/distributions/angular.py
  pycbc/distributions/bounded.py
  pycbc/distributions/gaussian.py
  pycbc/distributions/joint.py
  pycbc/distributions/power_law.py
  pycbc/distributions/uniform.py
  pycbc/distributions/uniform_log.py
  pycbc/inference/sampler/base_cube.py
  pycbc/inference/sampler/multinest.py
Labels: inference

#3276 foreground minifollowup sorting
  bin/minifollowups/pycbc_foreground_minifollowup
  bin/minifollowups/pycbc_page_coincinfo
  pycbc/workflow/minifollowups.py
Labels: offline search

#3278 Improve PyCBC Live unit test
  examples/live/check_results.py
  examples/live/run.sh
Labels: low latency

#3277 Fix warning when generating fake noise
  pycbc/psd/analytical.py
  pycbc/psd/estimate.py
  pycbc/strain/strain.py
Labels: python3

#3267 allow external distributions if you can provide a logpdf and cdfinv function
  examples/inference/analytic-normal2d/posterior-normal2d.png
  pycbc/distributions/__init__.py
  pycbc/distributions/external.py
  test/test_distributions.py
Labels: inference

#3282 Use floor division where integers are expected
  bin/plotting/pycbc_plot_waveform
  bin/pycbc_banksim
  examples/overlap.py
  pycbc/filter/matchedfilter.py
  pycbc/filter/resample.py
  pycbc/noise/reproduceable.py
  pycbc/strain/strain.py
  test/test_matchedfilter.py
Labels: python3

#3281 Pycbc geom nonspin python3
  bin/bank/pycbc_geom_nonspinbank
Labels: python3

#3265 add checkpointing to pycbc inspiral
  bin/pycbc_inspiral
  pycbc/events/eventmgr.py
  pycbc/inference/io/__init__.py
  pycbc/inference/io/base_hdf.py
  pycbc/io/hdf.py
Labels: offline search

#3284 Add xml foreground into multiifo workflow
  bin/workflows/pycbc_create_offline_search_workflow
Labels: offline search

#3280 Add standard newsnr fitting below fit threshold
  bin/hdfcoinc/pycbc_fit_sngls_split_binned
  pycbc/events/stat.py
Labels: offline search

#3289 Missed fix to sort order in foreground followup
  bin/minifollowups/pycbc_foreground_minifollowup
  bin/minifollowups/pycbc_page_coincinfo
Labels: offline search

#3288 Add support for dynesty's dynamic nested sampler
  pycbc/inference/sampler/dynesty.py
Labels: enhancement

#3246 Add dtphase plots
  bin/hdfcoinc/pycbc_plot_multiifo_dtphase
Labels: offline search
