Repository gwastro/pycbc, pull requests merged in 2020-04, with the labels that each got.

#3202 Prior histogram efficiency
  bin/hdfcoinc/pycbc_multiifo_dtphase
  pycbc/events/stat.py
Labels: offline search

#3209 Add code for foreground loudest events table in multiifo format
  bin/hdfcoinc/pycbc_multiifo_page_foreground
Labels: offline search

#3212 make foreground table in workflow
  bin/workflows/pycbc_create_offline_search_workflow
Labels: offline search

#3214 JointDistribution: introduce loop for renormalization due to constraints, and improve documentation
  pycbc/distributions/joint.py
Labels: inference

#3215 Allow for more flexible substitution from injections in config file
  pycbc/inference/models/gaussian_noise.py
Labels: enhancement, inference

#3217 PTA histogram - wrap phase, remove extraneous snr ratio bins
  bin/hdfcoinc/pycbc_multiifo_dtphase
Labels: offline search

#3218 Add colorbar labels to foundmissed plots. General tidy-up of the foundmissed script
  bin/hdfcoinc/pycbc_page_foundmissed
Labels: offline search

#3224 Generalize relative model to all frequency domain approximants
  docs/_include/inference_example_relative.sh
  docs/inference/examples/relative.rst
  examples/inference/relative/get.sh
  examples/inference/relative/plot.sh
  examples/inference/relative/relative.ini
  examples/inference/relative/run.sh
  pycbc/inference/models/__init__.py
  pycbc/inference/models/relbin.py
  tools/pycbc_test_suite.sh
Labels: enhancement, inference

#3225 Add link to relative model documentation page
  docs/inference.rst
Labels: bug, inference

#3219 Multiifo page_ifar
  bin/hdfcoinc/pycbc_page_ifar
  bin/workflows/pycbc_create_offline_search_workflow
Labels: offline search

#3230 ifar_catalog bug
  bin/plotting/pycbc_ifar_catalog
Labels: bug

#3216 changes to PTA histogram normalisation
  pycbc/events/stat.py
Labels: offline search

#3232 Add option to plot waveform track on top of qscan
  bin/plotting/pycbc_plot_qscan
Labels: enhancement

#3133 split_binned histogram plots dealing with low numbers of triggers
  bin/hdfcoinc/pycbc_fit_sngls_split_binned
Labels: bug, offline search

#3240 multiifo_dtphase time size
  bin/hdfcoinc/pycbc_multiifo_dtphase
Labels: bug, offline search
