Repository gwastro/pycbc, pull requests merged in 2020-11, with the labels that each got.

#3518 coinc_mergetrigs: deduplicate livetime segments
  bin/hdfcoinc/pycbc_coinc_mergetrigs
Labels: offline search

#3522 update retention levels for opt_snr jobs in parallelised cases
  pycbc/workflow/injection.py
Labels: offline search

#3498 add script to monitor an inference job and generate updated plots and results page when it updates
  bin/inference/pycbc_inference_monitor
  pycbc/workflow/core.py
Labels: inference

#3523 Fix bug in redshift from comoving volume interpolator
  pycbc/cosmology.py
Labels: bug

#3528 fix bug for mean mchirp m_tot in coinc inspiral table
  pycbc/io/hdf.py
Labels: bug, offline search

#3529 Improve pycbc_plot_vt_ratio
  bin/plotting/pycbc_plot_vt_ratio
  pycbc/results/metadata.py
Labels: enhancement
