Repository gwastro/pycbc, pull requests merged in 2020-08, with the labels that each got.

#3409 save pvalue if used in far
  bin/pycbc_live
Labels: low latency

#3322 PyCBC Live Test w/ Multiple HDF injections
  examples/live/check_results.py
  examples/live/generate_injections.py
  examples/live/generate_injections.sh
  examples/live/run.sh
Labels: low latency

#3416 Fix exception handling in inference data utils module
  pycbc/inference/models/data_utils.py
Labels: inference

#3286 MultiIFO workflow singles development
  bin/hdfcoinc/pycbc_multiifo_sngls_findtrigs
  bin/hdfcoinc/pycbc_multiifo_sngls_pastro
  bin/minifollowups/pycbc_page_snglinfo
  pycbc/events/coinc.py
  pycbc/events/stat.py
Labels: offline search

#3413 Parallelize optimal_snr jobs
  bin/pycbc_optimal_snr
  pycbc/workflow/injection.py
Labels: offline search

#3412 speed up trigger fitting
  bin/hdfcoinc/pycbc_fit_sngls_by_template
  bin/hdfcoinc/pycbc_fit_sngls_over_multiparam
Labels: offline search

#3385 open up nested sampling to complicated / arbitrary distributions with fixed sample distribution
  pycbc/conversions.py
  pycbc/distributions/__init__.py
  pycbc/distributions/fixedsamples.py
  pycbc/transforms.py
  test/test_distributions.py
Labels: inference
