Repository gwastro/pycbc, pull requests merged in 2020-12, with the labels that each got.

#3541 Allow extract samples to handles nans
  bin/inference/pycbc_inference_extract_samples
Labels: bug, inference

#3381 Silence warnings from child nodes in MPI
  bin/inference/pycbc_inference
Labels: inference

#3559 Cleanup PyCBC Live example
  examples/live/.gitignore
  examples/live/check_results.py
  examples/live/generate_injections.py
  examples/live/run.sh
Labels: low latency

#3561 Simplify injections in PyCBC Live's example
  examples/live/.gitignore
  examples/live/generate_injections.py
  examples/live/run.sh
Labels: low latency

#3569 Add more info to offline GraceDB uploads
  bin/pycbc_upload_xml_to_gracedb
  pycbc/io/live.py
Labels: offline search
