Repository gwastro/pycbc, pull requests merged in 2021-01, with the labels that each got.

#3415 add options to pycbc_create_injections for use with offline search codes
  bin/pycbc_create_injections
Labels: offline search

#3573 simplify strain from cli, move injections after resample
  pycbc/filter/resample.py
  pycbc/inject/inject.py
  pycbc/strain/strain.py
  pycbc/types/timeseries.py
Labels: 3g-detectors

#3484 Add numerical phimarg model
  pycbc/inference/models/__init__.py
  pycbc/inference/models/gaussian_noise.py
  pycbc/inference/models/marginalized_gaussian_noise.py
Labels: enhancement, inference

#3575 add script to convert xml injection file to hdf
  bin/bank/pycbc_coinc_bank2hdf
  bin/pycbc_inspinj2hdf
Labels: offline search

#3582 Included an option to choose the scipy optimizer
  bin/pycbc_optimize_snr
Labels: low latency

#3583 PyCBC Live: use Astropy to get a more precise current GPS time
  bin/pycbc_live
  pycbc/__init__.py
  pycbc/frame/frame.py
Labels: low latency

#3588 set fake strain options, sample rate, filter settings, etc
  pycbc/noise/reproduceable.py
  pycbc/strain/strain.py
  test/test_noise.py
Labels: 3g-detectors, LISA

#3589 Move interpolation into new parent class of WorkflowConfigParser
  pycbc/types/config.py
  pycbc/workflow/configuration.py
Labels: work in progress

#3603 fix plive test
  examples/live/check_results.py
  examples/live/run.sh
  pycbc/strain/strain.py
  pycbc/types/timeseries.py
Labels: low latency

#3605 Only accept points that have larger logl in dynesty rwalk
  pycbc/inference/sampler/dynesty.py
Labels: inference
