Repository gwastro/pycbc, pull requests merged in 2021-12, with the labels that each got.

#3878 Allow decimation thresholds in any order and with negative values
  bin/all_sky_search/pycbc_coinc_findtrigs
  examples/search/analysis.ini
Labels: offline search

#3898 fix erroneous leftover variable in error message
  bin/pycbc_optimize_snr
Labels: low latency

#3756 Integration of pygrb aligntotalspin functionality into pycbc/transforms.py as a class
  pycbc/pnutils.py
  pycbc/transforms.py
  pycbc/waveform/waveform_modes.py
Labels: PyGRB
