Repository gwastro/pycbc, pull requests merged in 2021-06, with the labels that each got.

#3728 Fix for broken pycbc_make_inference_inj_workflow
  pycbc/inject/inject.py
Labels: bug, inference

#3730 fix hdf injfilterrejector, speed up tau0 selection
  pycbc/inject/inject.py
  pycbc/waveform/bank.py
Labels: bug, offline search

#3731 parallelize coinc code, use shared memory
  bin/all_sky_search/pycbc_coinc_findtrigs
Labels: enhancement, offline search
