Repository gwastro/pycbc, pull requests merged in 2022-11, with the labels that each got.

#4061 PyGRB Workflow Generation Updates
  bin/pycbc_hdf_splitinj
  bin/pycbc_multi_inspiral
  bin/pygrb/pycbc_grb_inj_finder
  bin/pygrb/pycbc_grb_trig_combiner
  bin/pygrb/pycbc_make_offline_grb_workflow
  pycbc/workflow/grb_utils.py
  pycbc/workflow/injection.py
  pycbc/workflow/jobsetup.py
  pycbc/workflow/matched_filter.py
  pycbc/workflow/segment.py
  pycbc/workflow/splittable.py
Labels: PyGRB

#4168 Use solid sphere moment of inertia
  pycbc/conversions.py
Labels: bug

#4173 Analytic Kerr ISCO calculation for EM-bright code
  pycbc/neutron_stars/pg_isso_solver.py
Labels: PyGRB

#4159 Adding per-event-type live pastro
  bin/pycbc_live
  bin/pycbc_make_skymap
  bin/pycbc_optimize_snr
  pycbc/events/coinc.py
  pycbc/io/live.py
  pycbc/population/live_pastro.py
  pycbc/population/live_pastro_utils.py
  test/test_io_live.py
Labels: low latency

#4157 cleanup of pycbc live single trigger fits codes
  bin/all_sky_search/pycbc_coinc_findtrigs
  bin/all_sky_search/pycbc_sngls_findtrigs
  bin/live/pycbc_live_combine_single_fits
  bin/live/pycbc_live_plot_combined_single_fits
  bin/live/pycbc_live_plot_single_trigger_fits
  bin/live/pycbc_live_single_trigger_fits
  pycbc/events/cuts.py
Labels: low latency

#4186 Results page generation command
  bin/workflows/pycbc_make_coinc_search_workflow
Labels: offline search

#4190 fix corner case in live event followup
  pycbc/io/live.py
Labels: low latency

#4175 iDQ based veto in PyCBC Live
  bin/pycbc_live
  pycbc/frame/frame.py
  pycbc/strain/strain.py
Labels: low latency
