Repository gwastro/pycbc, pull requests merged in 2022-09, with the labels that each got.

#4106 Speed up psd computation for PyCBC Live
  bin/pycbc_live
  pycbc/psd/estimate.py
  pycbc/types/optparse.py
Labels: low latency

#4120 Fix serious bug(?) in PyCBC Live background estimate
  pycbc/events/coinc.py
Labels: low latency

#4121 Make no-mass-gap default option for online source classification
  bin/pycbc_live
  pycbc/mchirp_area.py
Labels: low latency

#4050 add statmap files for use with single-detector triggers
  bin/all_sky_search/pycbc_sngls_findtrigs
  bin/all_sky_search/pycbc_sngls_statmap
  bin/all_sky_search/pycbc_sngls_statmap_inj
  pycbc/events/significance.py
Labels: offline search

#4114 Cythonize logsignalrate
  bin/all_sky_search/pycbc_coinc_findtrigs
  pycbc/events/eventmgr_cython.pyx
  pycbc/events/stat.py
  test/test_live_coinc_compare.py
Labels: low latency

#4118 Use cython to expire pycbc live coinc buffer
  pycbc/events/coinc.py
  pycbc/events/eventmgr_cython.pyx
Labels: low latency

#4131 Small update to Sngl Buffer changes
  pycbc/events/coinc.py
Labels: low latency

#4136 Cythonize main part of ifar function
  pycbc/events/coinc.py
  pycbc/events/eventmgr_cython.pyx
  test/test_live_coinc_compare.py
Labels: low latency

#4126 Generate skymaps without sampling / enable pycbc inference to run model with only reconstructed params
  bin/inference/pycbc_inference
  bin/inference/pycbc_inference_model_stats
  docs/_include/inference_example_single_marg.sh
  docs/inference/examples/single.rst
  examples/inference/single/run_instant.sh
  examples/inference/single/single_instant.ini
  pycbc/inference/io/posterior.py
  pycbc/inference/models/tools.py
  pycbc/inference/sampler/__init__.py
  pycbc/inference/sampler/base.py
  pycbc/inference/sampler/dummy.py
Labels: inference

#4034 Change PyGRB plotting scripts to read HDF files
  bin/pygrb/pycbc_pygrb_plot_chisq_veto
  bin/pygrb/pycbc_pygrb_plot_coh_ifosnr
  bin/pygrb/pycbc_pygrb_plot_injs_results
  bin/pygrb/pycbc_pygrb_plot_null_stats
  bin/pygrb/pycbc_pygrb_plot_skygrid
  bin/pygrb/pycbc_pygrb_plot_snr_timeseries
  pycbc/results/pygrb_postprocessing_utils.py
Labels: work in progress, PyGRB
