Repository gwastro/pycbc, pull requests merged in 2022-10, with the labels that each got.

#4148 set consistent phase convention for inference models / maybe bugfix?
  pycbc/inference/models/gaussian_noise.py
  pycbc/inference/models/marginalized_gaussian_noise.py
  pycbc/inference/models/relbin_cpu.pyx
  pycbc/inference/models/single_template.py
  pycbc/inference/models/tools.py
Labels: inference

#4138 iDQ strain and frame support in PyCBC Live
  bin/pycbc_live
  pycbc/frame/__init__.py
  pycbc/frame/frame.py
  pycbc/strain/strain.py
  pycbc/types/timeseries.py
Labels: low latency

#4149 allow multiple cuts on same parameter
  pycbc/events/cuts.py
  test/test_cuts.py
Labels: offline search

#3937 Moving em_progenitors.py and ns_sequence data from tmpltbank to new neutron_stars package
  bin/pycbc_create_injections
  bin/pycbc_dark_vs_bright_injections
  pycbc/conversions.py
  pycbc/distributions/constraints.py
  pycbc/io/record.py
  pycbc/neutron_stars/__init__.py
  pycbc/neutron_stars/eos_utils.py
  pycbc/neutron_stars/ns_data/equil_2H.dat
  pycbc/neutron_stars/pg_isso_solver.py
  pycbc/tmpltbank/__init__.py
  pycbc/tmpltbank/coord_utils.py
  pycbc/tmpltbank/em_progenitors.py
  pycbc/tmpltbank/option_utils.py
  pycbc/waveform/parameters.py
  setup.py
Labels: PyGRB

#4141 Rework memory management of single-detector triggers
  pycbc/events/coinc.py
Labels: low latency

#4162 Fix a waveform plugin issue that missed the waveform length estimator
  pycbc/waveform/plugin.py
  pycbc/waveform/waveform.py
Labels: waveform
