Repository gwastro/pycbc, pull requests merged in 2022-03, with the labels that each got.

#3929 Moving multi_inspiral utils to coherent module
  bin/pycbc_multi_inspiral
  pycbc/events/coherent.py
Labels: PyGRB

#3965 PyCBC Live: explicitly log MPI commits and gathers
  bin/pycbc_live
Labels: low latency

#3947 Un-merged PyGRB post-processing development
  bin/pygrb/pycbc_grb_inj_combiner
  bin/pygrb/pycbc_grb_inj_finder
  bin/pygrb/pycbc_grb_trig_cluster
  bin/pygrb/pycbc_grb_trig_combiner
  bin/pygrb/pycbc_make_grb_summary_page
  bin/pygrb/pycbc_pygrb_efficiency
  bin/pygrb/pycbc_pygrb_grb_info_table
  bin/pygrb/pycbc_pygrb_minifollowups
  bin/pygrb/pycbc_pygrb_page_tables
  bin/pygrb/pycbc_pygrb_plot_chisq_veto
  bin/pygrb/pycbc_pygrb_plot_coh_ifosnr
  bin/pygrb/pycbc_pygrb_plot_injs_results
  bin/pygrb/pycbc_pygrb_plot_null_stats
  bin/pygrb/pycbc_pygrb_plot_skygrid
  bin/pygrb/pycbc_pygrb_plot_snr_timeseries
  bin/pygrb/pycbc_pygrb_plot_stats_distribution
  bin/pygrb/pycbc_pygrb_pp_workflow
  pycbc/results/__init__.py
  pycbc/results/pygrb_plotting_utils.py
  pycbc/results/pygrb_postprocessing_utils.py
  pycbc/results/static/css/pycbc/red.css
  pycbc/results/templates/red.html
  pycbc/workflow/plotting.py
Labels: PyGRB

#3946 add in some alternative smoothing methods
  bin/all_sky_search/pycbc_fit_sngls_over_multiparam
Labels: offline search

#3980 Results page artefact location
  examples/search/analysis.ini
  examples/search/gen.sh
Labels: bug

#3985 fix for dynesty reflect rename
  pycbc/inference/sampler/dynesty.py
Labels: work in progress
