Repository gwastro/pycbc, pull requests merged in 2022-02, with the labels that each got.

#3926 update page_foreground hdf output to match 4-ogc summary file
  bin/all_sky_search/pycbc_add_statmap
  pycbc/io/hdf.py
Labels: offline search

#3599 added Left and Right Circular Projection matrix
  bin/pycbc_multi_inspiral
Labels: PyGRB

#3927 Let `pycbc_optimize_snr` understand scheme and FFT options
  bin/pycbc_live
  bin/pycbc_optimize_snr
Labels: low latency

#3923 Fix in from_ligolw_table
  pycbc/io/record.py
Labels: PyGRB

#3930 Fix a few issues in `pycbc_optimize_snr`
  bin/pycbc_live
  bin/pycbc_optimize_snr
Labels: low latency

#3931 Run SNR optimizer in PyCBC Live example/test
  examples/live/.gitignore
  examples/live/run.sh
Labels: low latency

#3936 PyCBC Live: stop uploading PSDs to GraceDB as separate files
  pycbc/io/live.py
Labels: low latency
