Repository gwastro/pycbc, pull requests merged in 2023-06, with the labels that each got.

#4209 Add a Fisher distribution for sky locations
  pycbc/conversions.py
  pycbc/distributions/__init__.py
  pycbc/distributions/sky_location.py
  test/test_distributions.py
Labels: PyGRB

#4390 Added an OSError exception to MKL check in __init__.py
  pycbc/__init__.py
Labels: bug

#4399 Remove default sections from get_subsections
  pycbc/types/config.py
Labels: bug

#4402 Exclude IFO sections when looping through the get_subsections
  examples/search/plotting.ini
  pycbc/workflow/core.py
  pycbc/workflow/minifollowups.py
  pycbc/workflow/plotting.py
Labels: bug

#4386 Offline singles in workflow
  bin/minifollowups/pycbc_page_coincinfo
  bin/plotting/pycbc_page_ifar
  bin/plotting/pycbc_page_snrifar
  bin/plotting/pycbc_page_snrratehist
  bin/plotting/pycbc_plot_singles_vs_params
  bin/workflows/pycbc_make_offline_search_workflow
  docs/apps.rst
  docs/workflow/pycbc_make_offline_search_workflow.rst
  examples/search/analysis.ini
  examples/search/executables.ini
  examples/search/gen.sh
  pycbc/events/stat.py
  pycbc/workflow/coincidence.py
  tools/static/needs_full_build
  tools/test_coinc_search_workflow.sh
Labels: offline search

#4407 significance bug for trigger_fit
  pycbc/events/significance.py
Labels: offline search

#4364 Upgrades to pycbc_grb_inj_finder
  bin/pygrb/pycbc_grb_inj_finder
Labels: PyGRB

#4176 pycbc_optimize_snr: Implement mass dependent bounds on spin parameters
  bin/pycbc_optimize_snr
Labels: low latency

#4417 update two LISA docs
  docs/inference/examples/lisa_smbhb_ldc_pe.rst
  examples/inference/lisa_smbhb_inj/injection_smbhb.ini
  examples/inference/lisa_smbhb_inj/lisa_smbhb_relbin.ini
  examples/inference/lisa_smbhb_ldc/lisa_smbhb_relbin.ini
Labels: inference, LISA

#4380 Allow pycbc_multi_inspiral to search over a sky grid
  bin/pycbc_multi_inspiral
  examples/multi_inspiral/run.sh
Labels: PyGRB

#4389 add TDI AE PSD with confusion noise for LISA
  pycbc/psd/analytical.py
  pycbc/psd/analytical_space.py
Labels: LISA

#4299 EM brute
  bin/bank/pycbc_brute_bank
  pycbc/conversions.py
  pycbc/io/record.py
  pycbc/neutron_stars/eos_utils.py
Labels: PyGRB

#4421 Prevent duplicates of the HLV page_ifar plot on the summary page
  bin/workflows/pycbc_make_offline_search_workflow
Labels: bug, offline search
