Repository gwastro/pycbc, pull requests merged in 2023-04, with the labels that each got.

#4302 Proposed fix for 4270
  pycbc/events/coinc.py
Labels: low latency

#4291 Flag cases when PyCBC Live's IFAR and/or followup p-values are saturated
  bin/pycbc_live
  pycbc/events/coinc.py
  pycbc/filter/matchedfilter.py
Labels: low latency

#4310 add option to set number of sky points in precalculation
  pycbc/inference/models/tools.py
Labels: inference

#4311 Live single trigger fits clustering Bugfix
  bin/live/pycbc_live_single_trigger_fits
Labels: bug, low latency

#4314 Add label to SNR optimizer uploads
  bin/pycbc_live
  bin/pycbc_optimize_snr
Labels: low latency

#4318 fix small issues with LISA sensitivity curve
  pycbc/psd/analytical_space.py
Labels: LISA

#4306 Modify HasMassGap to be optional and customizable
  bin/pycbc_live
  pycbc/io/live.py
Labels: low latency

#4328 Can't generate array directly from dict keys object
  bin/bank/pycbc_aligned_stoch_bank
  bin/bank/pycbc_bank_verification
  pycbc/tmpltbank/partitioned_bank.py
Labels: bug

#4298 Make autogating work for the PyCBC Live early-warning search
  bin/pycbc_live
  pycbc/strain/strain.py
Labels: enhancement, low latency

#4322 more physical rwrap for LISA SMBHB/SOBHB injection
  companion.txt
  pycbc/waveform/waveform.py
  requirements.txt
  setup.py
Labels: LISA, waveform

#4327 Allow cuts on a multiple of the median sigma value
  bin/all_sky_search/pycbc_coinc_findtrigs
  bin/all_sky_search/pycbc_sngls_findtrigs
  pycbc/events/cuts.py
Labels: offline search

#4332 Do not try uploading stuff if event creation failed
  pycbc/io/live.py
Labels: bug, low latency
