Repository gwastro/pycbc, pull requests merged in 2023-07, with the labels that each got.

#4288 Pygrb offline workflow
  bin/pycbc_multi_inspiral
  bin/pygrb/pycbc_make_offline_grb_workflow
  bin/pygrb/pycbc_pygrb_efficiency
  bin/pygrb/pycbc_pygrb_minifollowups
  bin/pygrb/pycbc_pygrb_page_tables
  bin/pygrb/pycbc_pygrb_plot_chisq_veto
  bin/pygrb/pycbc_pygrb_plot_coh_ifosnr
  bin/pygrb/pycbc_pygrb_plot_injs_results
  bin/pygrb/pycbc_pygrb_plot_null_stats
  bin/pygrb/pycbc_pygrb_plot_snr_timeseries
  bin/pygrb/pycbc_pygrb_pp_workflow
  pycbc/results/legacy_grb.py
  pycbc/results/pygrb_plotting_utils.py
  pycbc/results/pygrb_postprocessing_utils.py
  pycbc/workflow/core.py
  pycbc/workflow/grb_utils.py
  pycbc/workflow/injection.py
  pycbc/workflow/jobsetup.py
  pycbc/workflow/matched_filter.py
Labels: work in progress, PyGRB

#4423 only download LISA response file once
  pycbc/psd/analytical_space.py
Labels: LISA

#4346 Introduced a new arguement --skymap-only-ifos in pycbc_live
  bin/pycbc_live
  bin/pycbc_optimize_snr
  pycbc/io/live.py
Labels: low latency

#4350 more physical rwrap for LISA SMBHB/SOBHB injection (follow-up fix 2)
  pycbc/waveform/waveform.py
Labels: LISA, waveform

#4418 fftw_fix
  bin/pycbc_inspiral
Labels: bug

#4365 Add argument verification for singles
  bin/pycbc_live
  examples/live/check_results.py
  examples/live/run.sh
  pycbc/events/single.py
Labels: low latency

#4433 Rename --longitude and --latitude back to --ra and --dec
  bin/pycbc_multi_inspiral
  examples/multi_inspiral/run.sh
Labels: PyGRB

#4420 Purge fullinj / injfull analyses
  bin/all_sky_search/pycbc_add_statmap
  bin/all_sky_search/pycbc_coinc_hdfinjfind
  bin/all_sky_search/pycbc_coinc_statmap_inj
  bin/all_sky_search/pycbc_sngls_statmap_inj
  bin/workflows/pycbc_make_offline_search_workflow
  examples/search/analysis.ini
  pycbc/workflow/coincidence.py
Labels: offline search
