Repository gwastro/pycbc, pull requests merged in 2023-11, with the labels that each got.

#4543 Optimize memory usage of pycbc_fit_sngls_split_binned
  bin/all_sky_search/pycbc_fit_sngls_split_binned
Labels: v23_release_branch

#4548 Non-coinc ifos in minifollowup trig plots
  bin/minifollowups/pycbc_foreground_minifollowup
  bin/minifollowups/pycbc_plot_trigger_timeseries
Labels: v23_release_branch

#4538 Modify stats_dist to utilize hdf
  bin/pygrb/pycbc_pygrb_plot_stats_distribution
Labels: PyGRB

#4533 [pycbc live] Allowing the use of psd variation in the ranking statistic for pycbc live
  bin/pycbc_live
  examples/live/run.sh
  pycbc/events/coinc.py
  pycbc/psd/variation.py
Labels: low latency

#4566 Fix plot_singles and optimize memory
  bin/plotting/pycbc_plot_singles_vs_params
Labels: v23_release_branch

#4549 Use gating windows in sngl_minifollowup and allow 'triggers within vetoes' option
  bin/minifollowups/pycbc_page_snglinfo
  bin/minifollowups/pycbc_sngl_minifollowup
  bin/workflows/pycbc_make_offline_search_workflow
  pycbc/events/stat.py
  pycbc/io/hdf.py
  pycbc/workflow/minifollowups.py
Labels: offline search, v23_release_branch

#4569 Fix over-verbose offline workflow generator after init_logging change
  bin/workflows/pycbc_make_offline_search_workflow
Labels: bug, offline search

#4571 Fix bug with numpy import in pycbc_coinc_findtrigs
  bin/all_sky_search/pycbc_coinc_findtrigs
Labels: bug
