Repository gwastro/pycbc, pull requests merged in 2023-01, with the labels that each got.

#4177 State-of-the-art of timeslides development in pycbc_multi_inspiral
  bin/pycbc_multi_inspiral
  examples/multi_inspiral/check_gw170817_trigs.py
  examples/multi_inspiral/run.sh
  pycbc/events/coherent.py
  pycbc/events/eventmgr.py
Labels: PyGRB

#4187 Start GraceDB uploads and setup_optimize_snr process in threads
  bin/pycbc_live
  pycbc/io/live.py
Labels: low latency

#4241 Avoid memory leaks when one detector is down for a long time
  pycbc/events/coinc.py
Labels: low latency

#4172 generate LISA TDI-1.5/2.0 noise in PyCBC
  bin/bank/pycbc_geom_aligned_bank
  pycbc/io/ligolw.py
  pycbc/psd/__init__.py
  pycbc/psd/analytical.py
  pycbc/psd/analytical_space.py
  pycbc/strain/strain.py
  pycbc/types/optparse.py
Labels: work in progress, LISA

#4247 add PASTRO_READY label
  companion.txt
  pycbc/io/live.py
Labels: low latency

#4248 Lisa fix doc
  docs/inference/examples/lisa_smbhb.rst
  examples/inference/lisa_smbhb/get.sh
  pycbc/psd/analytical_space.py
Labels: LISA

#4223 Adding script for plotting histograms of triggers near gates
  bin/plotting/pycbc_plot_gate_triggers
Labels: enhancement, offline search
