Repository gwastro/pycbc, pull requests merged in 2023-12, with the labels that each got.

#4579 remove removal of downranked triggers
  bin/minifollowups/pycbc_plot_trigger_timeseries
Labels: offline search, v23_release_branch

#4580 update lalsimulation cvmfs path
  Dockerfile
  docker/etc/docker-install.sh
  docs/building_bundled_executables.rst
  docs/install.rst
  docs/install_lalsuite.rst
  docs/workflow/pycbc_make_offline_search_workflow.rst
  tools/cvmfs-default.local
Labels: bug

#4542 PyGRB postprocessing: segment writing/loading
  bin/pycbc_multi_inspiral
  pycbc/events/eventmgr.py
  pycbc/results/pygrb_postprocessing_utils.py
Labels: PyGRB

#4577 split/bin parameters in pycbc_fit_sngls_split_binned
  bin/all_sky_search/pycbc_fit_sngls_split_binned
Labels: offline search

#4586 [bug] Enforcing int types in pycbc_coinc_findtrigs
  bin/all_sky_search/pycbc_coinc_findtrigs
Labels: bug

#4582 Adding likelihood to multi_signal model for inference of LISA signals.
  examples/inference/lisa_smbhb_inj/lisa_smbhb_relbin.ini
  examples/inference/lisa_smbhb_ldc/lisa_smbhb_relbin.ini
  pycbc/inference/models/brute_marg.py
  pycbc/inference/models/relbin.py
  pycbc/inference/models/relbin_cpu.pyx
  pycbc/waveform/parameters.py
  pycbc/waveform/waveform.py
Labels: inference, LISA

#4513 Dev comments for the pycbc_multi_inspiral executable
  bin/pycbc_multi_inspiral
Labels: PyGRB

#4592 Do not set matplotlib's backend in internal modules
  bin/pycbc_make_skymap
  bin/pycbc_optimize_snr
  pycbc/io/live.py
Labels: low latency

#4593 bug in choosing the far calculation method
  bin/all_sky_search/pycbc_add_statmap
Labels: bug, offline search, v23_release_branch
