Repository gwastro/pycbc, pull requests merged in 2023-03, with the labels that each got.

#4272 changed order of gracedb upload
  pycbc/io/live.py
Labels: low latency

#4277 make sure array index is an integer
  bin/pycbc_single_template
Labels: python3

#4278 Truncate SNR/FAR for live pastro calcs
  pycbc/population/live_pastro.py
  pycbc/population/live_pastro_utils.py
Labels: low latency

#4287 Bug fix in pycbc_grb_inj_finder
  bin/pygrb/pycbc_grb_inj_finder
Labels: bug, PyGRB

#4292 Fix an issue of pycbc_page_injtable
  pycbc/results/table_utils.py
Labels: bug

#4203 add two heterodyne / relative likelihood models dedicated to sky marginalization
  examples/inference/relmarg/get.sh
  examples/inference/relmarg/reltime.ini
  examples/inference/relmarg/run.sh
  pycbc/inference/models/__init__.py
  pycbc/inference/models/relbin.py
  pycbc/inference/models/relbin_cpu.pyx
  pycbc/inference/models/tools.py
Labels: inference
