Repository gwastro/pycbc, pull requests merged in 2024-01, with the labels that each got.

#4597 Use vetoed times followup in example
  examples/search/plotting.ini
Labels: v23_release_branch

#4534 Scripts for dealing with preparation of offline gracedb upload files
  bin/all_sky_search/pycbc_make_bayestar_skymap
  bin/all_sky_search/pycbc_prepare_xml_for_gracedb
  bin/all_sky_search/pycbc_upload_single_event_to_gracedb
  pycbc/io/hdf.py
  pycbc/io/live.py
  pycbc/results/__init__.py
  pycbc/results/snr.py
Labels: offline search, v23_release_branch

#4485 Add the code to generate the sky grid that will be used by pycbc_multi_inspiral
  bin/pycbc_make_sky_grid
Labels: PyGRB

#4611 Fix psd len issue
  pycbc/psd/__init__.py
  pycbc/psd/estimate.py
Labels: LISA

#4600 Live: produce empty trigger fit plot for detectors with no triggers
  bin/live/pycbc_live_plot_single_trigger_fits
  bin/live/pycbc_live_single_trigger_fits
Labels: low latency
