Repository gwastro/pycbc, pull requests merged in 2024-07, with the labels that each got.

#4804 fix normalization of sky and time marginalization to reduce integral …
  pycbc/inference/models/relbin.py
  pycbc/inference/models/tools.py
Labels: inference

#4805 allow approximant to be read from config file
  bin/bank/pycbc_brute_bank
Labels: work in progress

#4810 Update pycbc_brute_bank
  bin/bank/pycbc_brute_bank
Labels: bug

#4697 Script to create hdf trigger merge files from PyCBC Live output trigger files
  bin/live/pycbc_live_collate_triggers
Labels: low latency

#4814 fix a memory leakage bug in pycbc_brute_bank
  bin/bank/pycbc_brute_bank
  pycbc/pool.py
Labels: bug

#4812 Adding marginalized line to pygrb_efficiency
  bin/pygrb/pycbc_pygrb_efficiency
Labels: PyGRB

#4820 PyGRB trigger clustering with short timeslides
  bin/pygrb/pycbc_grb_trig_cluster
Labels: PyGRB

#4819 Use singles FAR calculation properly in the example search
  examples/search/analysis.ini
Labels: bug

#4816 Add mechanism for re-loading the statistic files in live
  bin/pycbc_live
  pycbc/events/coinc.py
  pycbc/events/single.py
  pycbc/events/stat.py
  test/test_live_coinc_compare.py
Labels: low latency

#4813 Add a script to supervise template fitting in pycbc live
  bin/all_sky_search/pycbc_fit_sngls_by_template
  bin/all_sky_search/pycbc_fit_sngls_over_multiparam
  bin/live/pycbc_live_plot_single_significance_fits
  bin/live/pycbc_live_single_significance_fits
  bin/live/pycbc_live_supervise_collated_trigger_fits
  bin/live/pycbc_live_supervise_single_significance_fits
  bin/plotting/pycbc_plot_bank_corner
  pycbc/live/__init__.py
  pycbc/live/supervision.py
Labels: low latency

#4809 PyGRB: Propagating slide_id information across postprocessing plotting scripts
  bin/pygrb/pycbc_pygrb_plot_chisq_veto
  bin/pygrb/pycbc_pygrb_plot_coh_ifosnr
  bin/pygrb/pycbc_pygrb_plot_null_stats
  bin/pygrb/pycbc_pygrb_plot_snr_timeseries
  pycbc/results/pygrb_postprocessing_utils.py
Labels: PyGRB

#4830 don't forget to actually deploy the documentation
  .github/workflows/basic-tests.yml
Labels: bug

#4834 support python3.12 now, so use bbhx master
  docs/_include/inference_example_lisa_smbhb_inj.sh
  docs/_include/inference_example_lisa_smbhb_ldc.sh
  docs/inference/examples/lisa_smbhb_inj_pe.rst
  docs/inference/examples/lisa_smbhb_ldc_pe.rst
  tox.ini
Labels: LISA, waveform
