Repository gwastro/pycbc, pull requests merged in 2024-03, with the labels that each got.

#4657 avoid using for loop in space psds; fix typo
  pycbc/psd/analytical_space.py
Labels: LISA

#4653 Update how live fitting deals with invalid values
  bin/live/pycbc_live_combine_single_fits
  bin/live/pycbc_live_plot_combined_single_fits
  pycbc/events/single.py
Labels: low latency

#4672 specify an older branch of BBHx in tox.ini
  tox.ini
Labels: LISA

#4505 add JointPrimaryMarginalizedModel likelihood model
  pycbc/inference/models/__init__.py
  pycbc/inference/models/base_data.py
  pycbc/inference/models/hierarchical.py
  pycbc/inference/models/relbin.py
  pycbc/inference/models/tools.py
Labels: work in progress, inference, LISA, multiband

#4680 file handler no longer exists, so will fail if closed
  pycbc/inference/io/base_hdf.py
Labels: bug
