Repository gwastro/pycbc, pull requests merged in 2024-08, with the labels that each got.

#4831 Add checksums to hdf5 datasets datasets
  pycbc/io/hdf.py
Labels: enhancement, offline search, PyGRB

#4836 PyCBC Live: fix errors from stat refresh code when not being used
  bin/pycbc_live
  pycbc/events/coinc.py
  pycbc/events/single.py
Labels: bug, low latency

#4838 Fix subtle bug when using `LIGOTimeGPS` with `TimeSeries.at_time()`
  pycbc/types/timeseries.py
  test/test_timeseries.py
Labels: bug

#4843 Use more f-strings in `pycbc_live`
  bin/pycbc_live
Labels: low latency

#4846 Fix small typo in pycbc_live_supervise_collated_trigger_fits
  bin/live/pycbc_live_supervise_collated_trigger_fits
Labels: bug, low latency

#4841 Try to copy #4789 for v23_release_branch
  .github/workflows/distribution.yml
  pycbc/inference/sampler/emcee_pt.py
  pyproject.toml
  requirements.txt
  setup.py
Labels: v23_release_branch

#4839 Various improvements to minifollowup tables
  bin/minifollowups/pycbc_page_coincinfo
  bin/minifollowups/pycbc_page_injinfo
  bin/minifollowups/pycbc_page_snglinfo
  examples/search/plotting.ini
  pycbc/results/dq.py
  pycbc/results/static/css/pycbc/orange.css
  pycbc/results/table_utils.py
Labels: enhancement, offline search

#4824 Fix sngls_minifollowup event selection/ordering [v23_release_branch]
  bin/minifollowups/pycbc_sngl_minifollowup
  pycbc/io/hdf.py
Labels: v23_release_branch

#4852 remove readfp (Python 3.12 removes it), use read_file instead
  pycbc/types/config.py
Labels: inference
