Repository gwastro/pycbc, pull requests merged in 2024-02, with the labels that each got.

#4615 fix thinko in option parsing for defaults
  pycbc/live/snr_optimizer.py
Labels: bug, low latency

#4509 Improvements to single fit plots
  bin/live/pycbc_live_plot_combined_single_fits
  bin/live/pycbc_live_plot_single_trigger_fits
Labels: low latency

#4545 Some changes to HFile.select() and SingleDetTriggers
  bin/all_sky_search/pycbc_bin_trigger_rates_dq
  bin/all_sky_search/pycbc_fit_sngls_split_binned
  bin/minifollowups/pycbc_injection_minifollowup
  bin/minifollowups/pycbc_page_snglinfo
  bin/minifollowups/pycbc_plot_trigger_timeseries
  bin/minifollowups/pycbc_sngl_minifollowup
  bin/plotting/pycbc_plot_hist
  bin/plotting/pycbc_plot_singles_timefreq
  bin/plotting/pycbc_plot_singles_vs_params
  bin/pycbc_fit_sngl_trigs
  bin/pycbc_process_sngls
  docs/hwinj.rst
  examples/search/plotting.ini
  pycbc/events/ranking.py
  pycbc/io/hdf.py
Labels: offline search

#4535 Workflow changes needed to manage offline gracedb upload prep
  bin/minifollowups/pycbc_foreground_minifollowup
  bin/minifollowups/pycbc_injection_minifollowup
  bin/minifollowups/pycbc_sngl_minifollowup
  bin/minifollowups/pycbc_upload_prep_minifollowup
  bin/workflows/pycbc_make_offline_search_workflow
  pycbc/workflow/minifollowups.py
  pycbc/workflow/psd.py
Labels: offline search

#4502 PyGRB: Sky-error plot fix
  bin/pygrb/pycbc_pygrb_plot_injs_results
Labels: PyGRB

#4630 Fix broken --version option
  pycbc/_version.py
  pycbc/_version_helper.py
  tools/pycbc_test_suite.sh
Labels: bug, v23_release_branch

#4628 [pycbc_live] Simplify and fix how CLI options are passed to the SNR optimizer
  bin/pycbc_live
  examples/live/run.sh
  pycbc/live/snr_optimizer.py
Labels: bug, low latency

#4550 PyGRB: Update postprocessing functions
  bin/pygrb/pycbc_grb_inj_finder
  bin/pygrb/pycbc_grb_trig_combiner
  bin/pygrb/pycbc_make_offline_grb_workflow
  pycbc/results/pygrb_postprocessing_utils.py
  pycbc/workflow/grb_utils.py
Labels: PyGRB

#4562 Update PyGRB efficiency script for HDF files
  bin/pygrb/pycbc_pygrb_efficiency
Labels: PyGRB

#4636 Bug: Live combine fits, different bin edge sizes causes an error
  bin/live/pycbc_live_combine_single_fits
Labels: bug, low latency

#4635 Improve how pycbc_live handles localization-only detectors
  bin/pycbc_live
Labels: low latency

#4644 Bugfix: upload prep read psds function
  bin/all_sky_search/pycbc_prepare_xml_for_gracedb
Labels: bug, offline search

#4646 Fix issue with string format in reading LVK HDF format injection files
  bin/pycbc_convertinjfiletohdf
Labels: offline search, v23_release_branch

#4587 Add pycbc support for the snowline sampler
  bin/inference/pycbc_inference_model_stats
  companion.txt
  docs/inference/examples/sampler_platter.rst
  examples/inference/samplers/run.sh
  examples/inference/samplers/snowline_stub.ini
  pycbc/inference/io/__init__.py
  pycbc/inference/io/snowline.py
  pycbc/inference/sampler/__init__.py
  pycbc/inference/sampler/snowline.py
  pycbc/pool.py
Labels: inference

#4301 add support for multi-returning-value functions in transform
  pycbc/transforms.py
Labels: inference
