Repository gwastro/pycbc, pull requests merged in 2025-02, with the labels that each got.

#5036 Added import to banksim_combine_banks
  bin/pycbc_banksim_combine_banks
Labels: bug

#5034 Combined plotifar
  bin/plotting/pycbc_page_fars_vs_stat
Labels: offline search

#5042 PyGRB: Veto fix #2
  pycbc/results/pygrb_postprocessing_utils.py
Labels: bug, PyGRB

#5038 PyGRB: minor fixes to workflow generator
  bin/pygrb/pycbc_make_offline_grb_workflow
  pycbc/workflow/jobsetup.py
Labels: bug, PyGRB

#5052 Fars_vs_stat plot in results page
  bin/plotting/pycbc_page_fars_vs_stat
  bin/workflows/pycbc_make_offline_search_workflow
  examples/search/executables.ini
  examples/search/plotting.ini
  pycbc/workflow/plotting.py
Labels: offline search

#5050 Avoid nan values in network volume term - MASTER VERSION
  pycbc/events/significance.py
  pycbc/events/stat.py
Labels: low latency

#5049 Avoid nan values in network volume term
  .github/workflows/basic-tests.yml
  bin/plotting/pycbc_plot_singles_vs_params
  bin/pycbc_multi_inspiral
  bin/pygrb/pycbc_make_offline_grb_workflow
  pycbc/events/significance.py
  pycbc/events/stat.py
  pycbc/waveform/decompress_cpu.py
  pycbc/workflow/jobsetup.py
  requirements.txt
  test/test_skymax.py
  tox.ini
Labels: low latency, v27_release_branch

#5056 Added check on spin magnitude
  pycbc/conversions.py
Labels: PyGRB

#5059 Improve conservative percentile calculation in live combining single …
  bin/live/pycbc_live_combine_single_significance_fits
  requirements.txt
Labels: low latency

#5055 Ranking statistic documentation fix
  docs/index.rst
  docs/search/ranking_statistic.rst
  docs/searches.rst
  docs/searches/ranking_statistic.rst
Labels: bug, documentation

#5061 Add statistic correction option
  pycbc/events/stat.py
Labels: offline search, v23_release_branch
