Repository gwastro/pycbc, pull requests merged in 2025-07, with the labels that each got.

#5152 np.unicode_ deprecated
  bin/pycbc_banksim_combine_banks
  bin/pycbc_banksim_match_combine
Labels: bug

#4537 Adding functionalities to create calibration config files
  bin/inference/pycbc_inference_create_calibration_config
  examples/inference/calibration_configuration_files/download_calibration_uncertainty_files_o1_o2_o3.sh
  examples/inference/calibration_configuration_files/generate_calibration_config.sh
  pycbc/strain/recalibrate.py
Labels: inference

#5157 Avoid unnecessary SNR (re)normalization in `multi_inspiral`
  bin/pycbc_multi_inspiral
Labels: PyGRB, v28_release_branch
