Repository gwastro/pycbc, pull requests merged in 2025-04, with the labels that each got.

#5098 Fix usage of release flag in Pegasus sites code
  pycbc/workflow/pegasus_sites.py
Labels: bug, v28_release_branch

#5099 Get LAL aux data from Zenodo and cache it
  .github/workflows/basic-tests.yml
Labels: github_actions

#5019 Move to igwn-ligolw
  bin/all_sky_search/pycbc_coinc_hdfinjfind
  bin/all_sky_search/pycbc_make_bayestar_skymap
  bin/all_sky_search/pycbc_prepare_xml_for_gracedb
  bin/all_sky_search/pycbc_sngls_pastro
  bin/all_sky_search/pycbc_strip_injections
  bin/bank/pycbc_aligned_bank_cat
  bin/bank/pycbc_bank_verification
  bin/bank/pycbc_geom_aligned_bank
  bin/bank/pycbc_tmpltbank_to_chi_params
  bin/hwinj/pycbc_generate_hwinj
  bin/minifollowups/pycbc_sngl_minifollowup
  bin/plotting/pycbc_page_segments
  bin/plotting/pycbc_page_vetotable
  bin/plotting/pycbc_plot_Nth_loudest_coinc_omicron.py
  bin/pycbc_banksim
  bin/pycbc_banksim_match_combine
  bin/pycbc_banksim_skymax
  bin/pycbc_convertinjfiletohdf
  bin/pycbc_faithsim
  bin/pycbc_faithsim_collect_results
  bin/pycbc_get_ffinal
  bin/pycbc_inj_cut
  bin/pycbc_make_banksim
  bin/pycbc_make_faithsim
  bin/pycbc_optimal_snr
  bin/pycbc_randomize_inj_dist_by_optsnr
  bin/pycbc_split_inspinj
  bin/pycbc_splitbank
  bin/pycbc_upload_xml_to_gracedb
  examples/live/check_results.py
  examples/workflow/dayhopecheck/dayhopecheck.py
  pycbc/dq.py
  pycbc/events/veto.py
  pycbc/inject/inject.py
  pycbc/io/gracedb.py
  pycbc/io/hdf.py
  pycbc/io/ligolw.py
  pycbc/io/record.py
  pycbc/psd/read.py
  pycbc/tmpltbank/bank_output_utils.py
  pycbc/types/frequencyseries.py
  pycbc/waveform/bank.py
  pycbc/workflow/core.py
  pycbc/workflow/datafind.py
  requirements.txt
  setup.py
  test/test_injection.py
  test/test_io_live.py
  tools/pycbc_test_suite.sh
  tools/timing/banksim/banksim.py
  tox.ini
Labels: dependencies

#5089 Upgrade Docker image and CVMFS virtualenv to newer Python
  Dockerfile
  tools/docker_build_dist.sh
Labels: on hold

#5107 Make pycbc_multi_inspiral way less verbose
  bin/pycbc_multi_inspiral
  pycbc/vetoes/autochisq.py
  pycbc/vetoes/bank_chisq.py
Labels: PyGRB, v28_release_branch

#5108 Ensure that the PyGRB offsource segmentlist contains ints
  pycbc/workflow/segment.py
Labels: bug, PyGRB, v28_release_branch

#5110 Dont use pylab, use pyplot directly
  bin/bank/pycbc_bank_verification
  bin/inference/pycbc_validate_test_posterior
  bin/minifollowups/pycbc_plot_chigram
  bin/minifollowups/pycbc_plot_trigger_timeseries
  bin/minifollowups/pycbc_single_template_plot
  bin/plotting/pycbc_faithsim_plots
  bin/plotting/pycbc_ifar_catalog
  bin/plotting/pycbc_page_banktriggerrate
  bin/plotting/pycbc_page_coinc_snrchi
  bin/plotting/pycbc_page_ifar
  bin/plotting/pycbc_page_segments
  bin/plotting/pycbc_page_segplot
  bin/plotting/pycbc_page_sensitivity
  bin/plotting/pycbc_page_snrchi
  bin/plotting/pycbc_page_snrifar
  bin/plotting/pycbc_page_snrratehist
  bin/plotting/pycbc_plot_background_coincs
  bin/plotting/pycbc_plot_bank_bins
  bin/plotting/pycbc_plot_gating
  bin/plotting/pycbc_plot_psd_file
  bin/plotting/pycbc_plot_psd_timefreq
  bin/plotting/pycbc_plot_range
  bin/plotting/pycbc_plot_singles_timefreq
  bin/plotting/pycbc_plot_singles_vs_params
  bin/plotting/pycbc_plot_throughput
  bin/population/pycbc_population_plots
  bin/pycbc_make_banksim
  bin/pycbc_make_faithsim
  pycbc/io/gracedb.py
  pycbc/results/followup.py
  pycbc/results/plot.py
  pycbc/results/snr.py
  test/lalsim.py
Labels: code-quality

#5114 Expand multi_inspiral examples and tests
  examples/multi_inspiral/check_gw170817_trigs.py
  examples/multi_inspiral/clean.sh
  examples/multi_inspiral/faceon_faceaway.sh
  examples/multi_inspiral/gw170817_h.sh
  examples/multi_inspiral/gw170817_hl.sh
  examples/multi_inspiral/gw170817_hlv.sh
  tools/pycbc_test_suite.sh
Labels: PyGRB, github_actions
